const state = { releases: [], selectedRelease: null, selectedDevice: null, downloaded: null, busy: false };
const $ = (id) => document.getElementById(id);
const escapeHtml = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatBytes = (n) => n ? `${(n / 1073741824).toFixed(2)} GB` : 'unknown size';
const osBrand = (os) => { const x=String(os).toLowerCase(); if(x.includes('android')) return ['Android','android.svg']; if(x.includes('debian')) return ['Debian','debian.svg']; if(x.includes('ubuntu')) return ['Ubuntu','ubuntu.svg']; if(x.includes('yocto')) return ['Yocto','yocto.svg']; return ['OS','']; };
function fillFilters() { const soms=[...new Set(state.releases.flatMap(r=>r.soms))].sort(); const oses=[...new Set(state.releases.map(r=>osBrand(r.os)[0]))].sort(); $('som').innerHTML='<option value="">All SOMs</option>'+soms.map(x=>`<option>${escapeHtml(x)}</option>`).join(''); $('os').innerHTML='<option value="">All OSes</option>'+oses.map(x=>`<option>${escapeHtml(x)}</option>`).join(''); }
function renderReleases() { const q=$('search').value.toLowerCase(), som=$('som').value, os=$('os').value; const items=state.releases.filter(r=>(!som||r.soms.includes(som))&&(!os||osBrand(r.os)[0]===os)&&(!q||JSON.stringify(r).toLowerCase().includes(q))); $('catalogStatus').textContent=`${items.length} releases found`; $('releases').innerHTML=items.map(r=>`<button class="release ${state.selectedRelease===r?'selected':''}" data-index="${state.releases.indexOf(r)}"><div class="release-brand">${osBrand(r.os)[1]?`<img src="./os-logos/${osBrand(r.os)[1]}" alt="${osBrand(r.os)[0]} logo">`:'<span class="os-fallback">OS</span>'}<div><strong>${escapeHtml(r.soms.join(' · '))}</strong><span>${escapeHtml(osBrand(r.os)[0])} · ${escapeHtml(r.os)}</span></div></div><div class="release-meta"><span>${escapeHtml(r.tag)}</span><time>${escapeHtml(r.date)}</time></div></button>`).join('')||'<p class="empty">No releases match the selected filters.</p>'; document.querySelectorAll('.release').forEach(b=>b.onclick=()=>selectRelease(state.releases[b.dataset.index])); }
async function selectRelease(r) { state.selectedRelease=r; state.downloaded=null; renderReleases(); $('selectionStatus').textContent='Loading release artifact details…'; try { r.details=await window.varFlasher.getRelease(r.pages[0].url); $('selectionStatus').textContent=r.details.downloadUrl?'Artifact found. Select an SD card and download it.':'This release has no published recovery artifact on its page.'; } catch(e) { $('selectionStatus').textContent=`Catalog error: ${e.message}`; } updateWrite(); }
async function loadDevices(silent=false) { if (!silent) $('deviceStatus').textContent='Scanning removable devices…'; try { const devices=await window.varFlasher.getDevices(); $('devices').innerHTML=devices.length?devices.map((d,i)=>`<button class="device ${state.selectedDevice?.path===d.path?'selected':''}" data-index="${i}"><strong>${escapeHtml(d.path)}</strong><span>${escapeHtml(d.model||'SD card')} · ${escapeHtml(d.size)} · ${escapeHtml(d.transport||'unknown')}</span></button>`).join(''):'<p class="empty">No removable writable disks detected.</p>'; document.querySelectorAll('.device').forEach(b=>b.onclick=()=>{state.selectedDevice=devices[b.dataset.index];loadDevices();updateWrite()}); $('deviceStatus').textContent=`${devices.length} removable device(s) found · monitoring automatically`; } catch(e){$('deviceStatus').textContent=`Device scan error: ${e.message}`;} }
function updateWrite(){const r=state.selectedRelease, d=state.selectedDevice; $('write').disabled=state.busy||!r?.details?.downloadUrl||!d; $('selectionTitle').textContent=r?`${r.soms.join(' · ')} — ${r.tag}`:'Ready to write'; $('selectionStatus').textContent=d?`Target ${d.path}. Everything on this disk will be erased.`:(r?.details?.downloadUrl?'Select a removable SD card.':'Select a release.');}
async function flash(){const r=state.selectedRelease,d=state.selectedDevice;if(!r||!d)return; if(!confirm(`This will erase ${d.path} completely. Continue?`))return; state.busy=true;updateWrite(); try { if(!state.downloaded){ const persist=confirm('Save this downloaded image in ~/.var-flasher/images for reuse?'); $('selectionStatus').textContent='Downloading and checking checksum…'; state.downloaded=await window.varFlasher.downloadImage(r.details,{persist}); const saved=persist?' Saved locally.':''; $('selectionStatus').textContent=`Download verified (SHA-256 ${state.downloaded.sha256}).${saved}`; } $('selectionStatus').textContent=`Writing ${formatBytes(state.downloaded.size)} to ${d.path}…`; const result=await window.varFlasher.writeImage({filePath:state.downloaded.path,device:d}); $('selectionStatus').textContent=`Success: ${formatBytes(result.bytes)} written and verified (SHA-256 ${result.sha256}).`; } catch(e){ $('selectionStatus').textContent=`Flash failed: ${e.message}`; } finally {state.busy=false;updateWrite();} }
window.varFlasher.onProgress(p=>{if(p.phase==='download')$('selectionStatus').textContent=`Downloading… ${p.total?Math.round(p.done/p.total*100):Math.round(p.done/1048576)+' MB'}`; if(p.phase==='verify')$('selectionStatus').textContent=`Verifying… ${p.total?Math.round(p.done/p.total*100):''}%`;});
$('search').oninput=renderReleases;$('som').onchange=renderReleases;$('os').onchange=renderReleases;$('refreshCatalog').onclick=loadCatalog;$('refreshDevices').onclick=loadDevices;$('write').onclick=flash;
async function loadCatalog(){ $('catalogStatus').textContent='Loading releases from dev.variscite.com…'; try{state.releases=await window.varFlasher.getCatalog();fillFilters();renderReleases()}catch(e){$('catalogStatus').textContent=`Catalog error: ${e.message}`;}}
loadCatalog();loadDevices(); setInterval(() => { if (!state.busy) loadDevices(true); }, 2500);